// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmV-j9sFrTkbqZ-dOrw-iiRrzaSVdIx2w',
    appId: '1:118629861048:web:e5005d834c770d0ab2164d',
    messagingSenderId: '118629861048',
    projectId: 'test-emotion-81f09',
    authDomain: 'test-emotion-81f09.firebaseapp.com',
    databaseURL: 'https://test-emotion-81f09-default-rtdb.firebaseio.com',
    storageBucket: 'test-emotion-81f09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALhJ2ARX5BMzl_APnvY9VL1JDl3dKHveM',
    appId: '1:118629861048:android:c52332df283633e5b2164d',
    messagingSenderId: '118629861048',
    projectId: 'test-emotion-81f09',
    databaseURL: 'https://test-emotion-81f09-default-rtdb.firebaseio.com',
    storageBucket: 'test-emotion-81f09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ31ujMC8w7AVedPPCUO6wdFxlbkihlyA',
    appId: '1:118629861048:ios:b824ae9f29b0606fb2164d',
    messagingSenderId: '118629861048',
    projectId: 'test-emotion-81f09',
    databaseURL: 'https://test-emotion-81f09-default-rtdb.firebaseio.com',
    storageBucket: 'test-emotion-81f09.appspot.com',
    iosBundleId: 'com.example.faceRecNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ31ujMC8w7AVedPPCUO6wdFxlbkihlyA',
    appId: '1:118629861048:ios:b824ae9f29b0606fb2164d',
    messagingSenderId: '118629861048',
    projectId: 'test-emotion-81f09',
    databaseURL: 'https://test-emotion-81f09-default-rtdb.firebaseio.com',
    storageBucket: 'test-emotion-81f09.appspot.com',
    iosBundleId: 'com.example.faceRecNew',
  );
}
